version: '3'

tasks:
  update:
    cmds:
      - go mod tidy
      - go clean all
      - go list -u -m all
      - go get -u ./...
  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy
  setup_fedora:
    cmds:
      - dnf install git gcc make -y
      - mkdir -p /src
      - cd /src
      - git clone https://github.com/libinjection/libinjection
      - gcc -std=c99 -Wall -Werror -fpic -c libinjection/src/libinjection_sqli.c -o libinjection/libinjection_sqli.o
      - gcc -std=c99 -Wall -Werror -fpic -c libinjection/src/libinjection_xss.c -o libinjection/libinjection_xss.o
      - gcc -std=c99 -Wall -Werror -fpic -c libinjection/src/libinjection_html5.c -o libinjection/libinjection_html5.o
      - gcc -dynamiclib -shared -o libinjection/libinjection.so libinjection/libinjection_sqli.o libinjection/libinjection_xss.o libinjection/libinjection_html5.o
      - cp libinjection/*.so /usr/local/lib
      - cp libinjection/*.o /usr/local/lib
      - cp libinjection/src/*.h /usr/local/include/
      - chmod 444 /usr/local/include/libinjection*
      - ldconfig
  build_linux64:
    desc: Build for prod for linux 64
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go mod download
      - go mod tidy
      - rm -rf ./dist/
      - go build -a -installsuffix cgo -o ./dist/ackycdn-node_linux_arm64.bin ackycdn.go
  podman:
    desc: Build docker image
  sec:
    cmds:
      - 'gosec -no-fail -stdout -verbose=text ./...' # -fmt=html -out=current_sec_report.html