version: '3'

tasks:
  update:
    cmds:
      - go mod tidy
      - go clean all
      - go list -u -m all
      - go get -u ./...
  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy
  build_linux64:
    desc: Build for prod for linux 64
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go mod download
      - go mod tidy
      - rm -rf ./dist/
      - go build -a -installsuffix cgo -o ./dist/ackycdn-node_linux_arm64.bin ackycdn.go
  podman:
    desc: Build docker image
    cmds:
      - podman build -f Dockerfile
  sec:
    cmds:
      - 'gosec -no-fail -stdout -verbose=text ./...' # -fmt=html -out=current_sec_report.html