version: '3'

tasks:
  update:
    cmds:
      - 'go mod tidy'
      - 'go clean all'
      - 'go list -u -m all'
      - 'go get -u ./...'
  sec:
    cmds:
      - 'gosec -no-fail -stdout -verbose=text ./...' # -fmt=html -out=current_sec_report.html